### PR TITLE
Fix GLES2 build error; convert to DUB package

### PR DESCRIPTION
**Pull request by buggins**
Could you please register this project as DUB package on code.dlang.org?

### CODE REVIEW

**Comment by joakim-noah** [comment]
Can you remove the dub.json commit?  I'll dig around for the one I wrote up and add that one instead.

**Comment by buggins** [comment]
Not sure how to remove commit.

**Comment by joakim-noah** [comment]
This should work:

git reset --hard HEAD~1
git push -f origin master

**Comment by buggins** [comment]
done

**Comment by joakim-noah** [comment]
Thanks, I'll try to get a dub.sdl in soon.

**Pull request merged**
